project:
  type: website
  output-dir: docs

website:
  title: "No Man's Land"
  navbar:
    right:
      - about.qmd
      # - icon: github
      #   href: https://github.com/snoringpig
format:
  html:
    theme: cosmo
    css: styles.css
